import React from 'react'
import { Download, RotateCcw, Heart, Sparkles } from 'lucide-react'

interface ResultCardProps {
  result: {
    imageUrl: string
    processingTime: string
  }
  onTryAgain: () => void
}

export default function ResultCard({ result, onTryAgain }: ResultCardProps) {
  const handleDownload = () => {
    const link = document.createElement('a')
    link.href = result.imageUrl
    link.download = `baby-face-${Date.now()}.png`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="max-w-md mx-auto">
      <div className="bg-white rounded-3xl shadow-2xl p-6 text-center">
        {/* Header */}
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-baby-purple mb-2 flex items-center justify-center gap-2">
            <Sparkles className="w-6 h-6" />
            Meet Your Future Baby!
            <Heart className="w-6 h-6 text-red-500" />
          </h2>
          <p className="text-baby-purple/70 text-sm">
            Generated in {result.processingTime}
          </p>
        </div>

        {/* Baby Image */}
        <div className="mb-6">
          <div className="relative inline-block">
            <img
              src={result.imageUrl}
              alt="Generated baby face"
              className="w-64 h-64 object-cover rounded-full border-8 border-baby-yellow shadow-xl mx-auto"
            />
            <div className="absolute -top-2 -right-2 bg-baby-pink text-white rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold">
              👶
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="space-y-3">
          <button
            onClick={handleDownload}
            className="w-full btn-primary flex items-center justify-center gap-2"
          >
            <Download className="w-5 h-5" />
            💾 Download HD Image
          </button>

          <button
            onClick={onTryAgain}
            className="w-full btn-secondary flex items-center justify-center gap-2"
          >
            <RotateCcw className="w-5 h-5" />
            Try Again with Different Photos
          </button>
        </div>

        {/* Watermark */}
        <div className="mt-6 pt-4 border-t border-baby-purple/20">
          <p className="text-xs text-baby-purple/50">
            Generated by BabyAI.app
          </p>
        </div>
      </div>
    </div>
  )
}
